### PR TITLE
Better unknown errors

### LINKED ISSUE #19: default_error_handler doesn't always return a full err: object
I noticed that sometimes the default_error_handler that is used by service-juttled's middleware doesn't always return a full err object. Instead the output looks like:

```
[Error: error running juttle: {"message":"Error from juttle compiler or runtime","code":"JS-JUTTLE-ERROR","info":{"err":{},"bundle"
```

I think the problem is that the err argument to JuttledErrors.unknownError might have to be stringified first.

### PR DESCRIPTION
**Pull request by mstemm**
Two changes that should reduce/eliminate the chances of a http response with an error but no meaningful details.

These changes should fix #19.

@VladVega @go-oleg @davidvgalbraith

### CODE REVIEW

File: lib/juttle-subprocess.js [hunk 1]
```diff
@@ -174,10 +175,24 @@ process.on('message', function(msg) {
             });
         })
         .catch(function(err) {
-            process.send({
-                type: 'compile_error',
-                err: err
-            });
+            // If it's a juttle error, return it with a compile_error
```
Comment (davidvgalbraith) [inline lib/juttle-subprocess.js]: This comment doesn't match the code.

**Comment by mstemm** [comment]
updated, can you look again?

**Comment by davidvgalbraith** [comment]
+1
