### PR TITLE
Don't dequeue from an empty message queue.

### LINKED ISSUE #17: Blank message sent over websocket
(Copied from juttle/outrigger#102)

When running a juttle program multiple times, sometimes blank messages come over the websocket from juttled:

image

juttle:
```
input a: text -label 'what';
emit -limit 1 | put v = 0 | view table;
```

Causes an exception in job-socket.js:

image

In my testing, this happens _most_ of the time. May have something to do with the duration between program runs.

From a git bisect, this behavior started happening in 60a60eeaed78bb36de9915612a5fc350eccc6029.

cc @dmehra who discovered this last night while running a more complicated juttle program.

cc @mstemm

### PR DESCRIPTION
**Pull request by mstemm**
When calling drain(), exit early when the message queue is empty. This
should be extremely uncommon, as drain() is only called as a part of a
call to send() or send_many(), both of which should add items to the
queue.

However, there is a potential race condition related to replaying
messages over a websocket where a client starts a job and connects to
the websocket before the juttle service has received the first point
from the subprocess. In that case, WebsocketJuttleJob's add_endpoint
method would call replay() on an empty list of _saved messages and
then call drain.

This could be fixed by not calling replay() when there are no saved
messages, but the safest place to fix the problem is to not dequeue
anything at all when the message queue is empty.

This fixes #17.

@go-oleg

### CODE REVIEW

File: lib/websocket-endpoint.js [hunk 1]
```diff
@@ -147,7 +147,8 @@ class WebsocketEndpoint {
     drain() {
         var self = this;
 
-        if (self._ws.readyState !== WebSocket.OPEN) {
+        if (self._ws.readyState !== WebSocket.OPEN ||
+            self._message_queue.isEmpty()) {
```
Comment (go-oleg) [inline lib/websocket-endpoint.js]: I agree with your comment that this is the right place to do this check. My understanding is  that it also makes it safe to call `drain()` multiple times back-to-back. Is that true/something we want to support and not have to defend against in other areas?

**Comment by go-oleg** [comment]
lgtm

File: lib/websocket-endpoint.js (hunk 1 above)
Comment (mstemm) [inline lib/websocket-endpoint.js]: I think it should be discouraged and the current code discourages it. If there were a way to make drain() private I would.

If you're thinking of lines 165 where it does a check for the queue being empty before calling drain again, I'd say keep that check, if only to make the base case cleaner (to me anyway).

Comment (go-oleg) [inline lib/websocket-endpoint.js]: Ah, I see. I think using underscores to convey privateness is a fine way to go. Or a comment above the function that it should be private.
